- .github/workflows/build.yml
- lazona_connector/settings.py
Allowing to optionally disable SSL connection to PostgreSQL and using that from the Github workflow. This ensures we use SSL by default, which feels safer.
> Setup PostgreSQL service in CI

- .gitignore
- koiki/client.py
- koiki/tests/test_client.py
Once again, we have to deal with a badly designed API. We'll complain to them but in the meantime, we better handle this.
> Handle ok status but failed koiki requests

- lazona_connector/settings.py
This is copied from
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment#getting_your_website_ready_to_publish.
> The value of the DEBUG will be True by default, but will only be False
if the value of the DJANGO_DEBUG environment variable is set to False.
Please note that environment variables are strings and not Python types.
We therefore need to compare strings. The only way to set the DEBUG
variable to False is to actually set it to the string False
> Configure DEBUG based on ENV var

- koiki/client.py
- koiki/order.py
- koiki/recipient.py
- koiki/sender.py
- koiki/tests/test_client.py
- koiki/tests/test_order.py
- koiki/tests/test_recipient.py
- koiki/tests/test_sender.py
Follow-up from #14
The API documentation states they are mandatory but the API response don't explicitly say so and we didn't inform them in our initial successful tests. Even the docs show examples passing `null`.
Note I undid the concatenation of address_1 and address_2 because it turns out Koiki's API has also the address optionally split into two fields. I purposefully skipped `direccionAdicionalRemi` though. We don't need it as the sender is hardcoded.
> Provide missing Koiki mandatory request params

- koiki/client.py
- koiki/tests/test_client.py
So request bodies can be seen in the console when running on INFO log level, which is the default when DEBUG is True, according to https://docs.djangoproject.com/en/3.1/topics/logging/#configuring-logging and https://github.com/django/django/blob/master/django/utils/log.py#L52-L63.
> Log to django.server logger

- api/tests/test_views.py
- koiki/tests/test_client.py
- koiki/tests/test_create_delivery.py
This is what both Woocommerce and Koiki do.
> Conform to ISO 3166-1 alpha-2 country name format

- api/host_authentication.py
- api/tests/test_host_authentication.py
- api/views.py
This implements a dummy custom authentication class that allows staging webhooks to pass through. This lets us work on #30 while collecting close-to-real traffic so we can debug the integration.
> Authenticate webhooks requests from staging

- api/host_authentication.py
- api/tests/test_host_authentication.py
It turns out Django transforms the header names:
> any HTTP headers in the request are converted to META keys by converting all characters to uppercase, replacing any hyphens with underscores and adding an HTTP_ prefix to the name.
source: https://docs.djangoproject.com/en/dev/ref/request-response/#django.http.HttpRequest.META
> Fix how to retrieve HTTP header

- api/tests/test_views.py
- koiki/client.py
So that the tests don't pick up the value we may have defined locally in the `.envrc` and they pass regardless.
> Load host from ENV at runtime

- koiki/client.py
This is necessary while troubleshooting why Koiki's API doesn't respond successfully. We don't know which combination of auth token and host works :(.
> Show client host in logs

- koiki/sender.py
- koiki/tests/test_client.py
- koiki/tests/test_sender.py
Closes #37. We mustn't forget to use the vendor's contact details when we change this.
> Use 9-digit phone number in Sender

- lazona_connector/settings.py
This way we don't need to add the ngrok's dynamic domain name each time we start a session locally.
> Allow ngrok subdomains in ALLOWED_HOSTS

- api/tests/__init__.py
- api/tests/test_views.py
- koiki/__init__.py
- koiki/client.py
- koiki/create_delivery.py
- koiki/models.py
- koiki/tests/__init__.py
- koiki/tests/test_client.py
- koiki/tests/test_create_delivery.py
- koiki/tests/test_models.py
- koiki/tests/test_wcfmmp.py
- koiki/tests/test_woocommerce_models.py
- koiki/woocommerce/models.py
- koiki/woocommerce/wcfmmp.py
This makes the integration fetch all the vendor details from the WCFM Marketplace's API (this the Woocommerce's Marketplace plugin we're using) as the sender's details to Koiki. That is, the details where the order needs to be picked up from.
We do so by calling `vendor.get()` right before creating the request body to be sent to Koiki's API. That's why I implemented an APIClient for WCFM which will use more and more.
This extra request makes it a must to start working on Celery ASAP so all this communication between APIs happens asynchronously. Now, it's very likely that WP (the webhook that triggers it all) will kill the request due to timeout.
While at it, I also DRYied and decoupled configuration settings from the tests and the classes using them and moved them to `__init__.py` files. …
> Fetch vendor details

- api/tests/__init__.py
- koiki/__init__.py
- koiki/client.py
- koiki/tests/__init__.py
- koiki/tests/test_client.py
- koiki/tests/test_wcfmmp.py
- koiki/woocommerce/wcfmmp.py
- lazona_connector/settings.py
This will silence all log messages by default. Things are getting very noisy. In any case, you can always remove this config when debugging tests.
This makes use of `LOGGING` which gets merged with Django's default logging settings. See https://docs.djangoproject.com/en/3.2/topics/logging/#configuring-logging.
It gets use from
```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.......[03/May/2021 14:31:45,445] Wcfmpp request. url=https://wcfmmp_testing_host/wp-json/wcfmmp/v1/settings/id/6
[03/May/2021 14:31:45,461] Koiki request to https://testing_host/rekis/api/altaEnvios. body={'formatoEtiqueta': 'PDF', 'envios': [{'numPedido': 'xxx', 'bultos': 1, 'kilos': 0.0, 'tipoServicio': '', 'reembolso': 0.0, 'observaciones': '', 'nombreDesti': …
```
> Silence logging in testing

- api/tests/__init__.py
- koiki/__init__.py
- koiki/client.py
- koiki/tests/__init__.py
This is the last missing piece of config that wasn't in __init__ yet. We finally decoupled Koiki's API client from these config details and things are a bit more changeable.
> Read AUTH_TOKEN from config in __init__

- api/tests/__init__.py
- koiki/__init__.py
- koiki/tests/__init__.py
- koiki/tests/test_wcfmmp.py
- koiki/woocommerce/wcfmmp.py
Closes #35. I missed the Basic Auth details and therefore requests to WP were failing. They now succeed which results in this workflow:
**[04/May/2021 15:03:11,634] Wcfmpp request. url=http://staging.lazona.coop/wp-json/wcfmmp/v1/settings/id/6**
[04/May/2021 15:03:12,951] Koiki request to https://rekistest.koiki.es/services/rekis/api/altaEnvios. body={'formatoEtiqueta': 'PDF', 'envios': [{'numPedido': 'wc_order_mtb7lqMmJRyfn', 'bultos': 1, 'kilos': 0.0, 'tipoServicio': '', 'reembolso': 0.0, 'observaciones': '', 'nombreDesti': 'Sergi', 'apellidoDesti': 'Alonso', 'direccionDesti': 'Travessera de Gràcia 264', 'direccionAdicionalDesti': '', 'numeroCalleDesti': '', 'codPostalDesti': '08025', 'poblacionDesti': 'Barcelona', 'provinciaDesti': 'B', 'paisDesti': 'ES', 'telefonoDesti': '653384286', …
> Authenticate wcfmmp requests

- lazona_connector/settings.py
- requirements.txt
Note this requires the ENV var `SENTRY_DSN` which is set up by Heroku when adding the Sentry's add-on from the UI.
> Install Sentry's SDK

- lazona_connector/settings.py
This gives room for the production environment in Heroku as well as the existing staging.
> Enable serving the app from N Heroku hosts

- api/authentication.py
- api/tests/__init__.py
- api/tests/test_signature_validation.py
- api/tests/test_views.py
- api/views.py
- lazona_connector/settings.py
There's no way we can configure Woocommerce (that I know of) to send a specific token provided by us as the HTTP Authorization header. As such, we can't rely on Django's REST Framework TokenAuthentication. Only on our SignatureValidation which implements Woocommerce's signature mechanism.
Also, given our custom authentication class needs to return a user record, it seemed best to return one that matches with these Woocommerce's webhooks when debugging things instead of forcing it to be super user. Pretty much like per-service users in Linux. This gives us room to change that user however we see fit in every environment.
> Use signature auth only

- lazona_connector/settings.py
Closes #19 
I expected Django to read these from ENV itself but it seems it does not. For instance, while the ENV var is set settings.SECURE_SSL_REDIRECT` returns `False` from a shell.
I chose to only override the setting if the matching ENV var is set otherwise, we default to Django's default value.
I only left an issue that may need more in-depth investigation
```sh
❯ heroku run python manage.py check --deploy -a lazona-connector-production                <<<
Running python manage.py check --deploy on ⬢ lazona-connector-production... up, run.4811 (Hobby)
System check identified some issues:
WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP …
```
> Configure stricter security-related settings

- api/tests/__init__.py
- docker-compose.yml
- koiki/tests/__init__.py
- lazona_connector/celery.py
Configuring Celery's results backend is becoming a bit tricky. Apparently, as I've seen in https://blog.heroku.com/securing-celery,
Redis doesn't support SSL so we need to purposefully disable SSL while using Redi's secure protocol (rediss://).
That's why I decided to make Celery's configuration a bit more explicit and greppeable moving it from ENV vars only to code. Without `ssl_cert_reqs` things won't work on Heroku so better to have a bit more obvious.
> Explicitly configure Celery's backend and broker

- lazona_connector/celery.py
This avoids E_REDIS_SSL_PARAMS_AND_SCHEME_MISMATCH exception due to adding the "ssl_cert_reqs" parameter when having a redis:// deployment.
> Avoids raising E_REDIS_SSL_PARAMS_AND_SCHEME_MISMATCH

- requirements.txt
I was expecting to see https://github.com/gabrielfalcao/HTTPretty/issues/388#issuecomment-840183825 but I'm afraid HTTPretty might be clashing with `responses` somehow and/or the duplicate initialization from api/tests/__init__.py and koiki/tests/__init__.py might be breaking things. Time to clean up.
> Upgrade HTTPretty to 1.1.3

- api/tasks.py
Due to celery order loading the apps. It doesn't know about the api app yet and throws error.
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
> Solving celery problem loading.

- .env.example
- .envrc.example
- api/admin.py
- api/tasks.py
- koiki/client.py
- koiki/delivery_create.py
- koiki/delivery_status.py
- koiki/delivery_update.py
- koiki/tests/test_client.py
- koiki/tests/test_create_delivery.py
- lazona_connector/vars.py
As we have 2 different API implementations for koiki I think it's best when client gets agnostic about which API are we using. Instead this responsibility is passed to CreateDelivery and UpdateDelivery classes
> make client simpler
